/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface IDInformation {
  'sex' : string,
  'weight' : string,
  'height' : string,
  'signature' : [] | [ExternalBlob],
  'dateOfBirth' : string,
  'eyeColor' : string,
  'photo' : [] | [ExternalBlob],
  'hairColor' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'trackingNumber' : [] | [string],
  'owner' : Principal,
  'paymentContactStatus' : PaymentContactStatus,
  'createdTime' : bigint,
  'email' : string,
  'shippingAddress' : ShippingAddress,
  'idInfo' : IDInformation,
  'phone' : string,
  'contactNotes' : string,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null };
export type PaymentContactStatus = { 'notContacted' : null } |
  { 'paymentReceived' : null } |
  { 'contacted' : null };
export interface ShippingAddress {
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptAdminInvitation' : ActorMethod<[], undefined>,
  'addOrUpdateTrackingNumber' : ActorMethod<[bigint, string], undefined>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'assignAdminRoleToCaller' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'checkAdminInvitation' : ActorMethod<[], boolean>,
  'createOrder' : ActorMethod<
    [string, string, string, ShippingAddress, IDInformation],
    bigint
  >,
  'declineAdminInvitation' : ActorMethod<[], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getBannedUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isBannedUser' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendAdminInvitation' : ActorMethod<[Principal], undefined>,
  'sendAdminInvitationByEmail' : ActorMethod<[string], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'updateOrder' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      ShippingAddress,
      IDInformation,
      OrderStatus,
      PaymentContactStatus,
      string,
    ],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updatePaymentContactStatus' : ActorMethod<
    [bigint, PaymentContactStatus, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];