/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShippingAddress = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const IDInformation = IDL.Record({
  'sex' : IDL.Text,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'signature' : IDL.Opt(ExternalBlob),
  'dateOfBirth' : IDL.Text,
  'eyeColor' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'hairColor' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
});
export const PaymentContactStatus = IDL.Variant({
  'notContacted' : IDL.Null,
  'paymentReceived' : IDL.Null,
  'contacted' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'trackingNumber' : IDL.Opt(IDL.Text),
  'owner' : IDL.Principal,
  'paymentContactStatus' : PaymentContactStatus,
  'createdTime' : IDL.Int,
  'email' : IDL.Text,
  'shippingAddress' : ShippingAddress,
  'idInfo' : IDInformation,
  'phone' : IDL.Text,
  'contactNotes' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptAdminInvitation' : IDL.Func([], [], []),
  'addOrUpdateTrackingNumber' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignAdminRoleToCaller' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'checkAdminInvitation' : IDL.Func([], [IDL.Bool], ['query']),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ShippingAddress, IDInformation],
      [IDL.Nat],
      [],
    ),
  'declineAdminInvitation' : IDL.Func([], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBannedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isBannedUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAdminInvitation' : IDL.Func([IDL.Principal], [], []),
  'sendAdminInvitationByEmail' : IDL.Func([IDL.Text], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'updateOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ShippingAddress,
        IDInformation,
        OrderStatus,
        PaymentContactStatus,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updatePaymentContactStatus' : IDL.Func(
      [IDL.Nat, PaymentContactStatus, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShippingAddress = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const IDInformation = IDL.Record({
    'sex' : IDL.Text,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'signature' : IDL.Opt(ExternalBlob),
    'dateOfBirth' : IDL.Text,
    'eyeColor' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'hairColor' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
  });
  const PaymentContactStatus = IDL.Variant({
    'notContacted' : IDL.Null,
    'paymentReceived' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'trackingNumber' : IDL.Opt(IDL.Text),
    'owner' : IDL.Principal,
    'paymentContactStatus' : PaymentContactStatus,
    'createdTime' : IDL.Int,
    'email' : IDL.Text,
    'shippingAddress' : ShippingAddress,
    'idInfo' : IDInformation,
    'phone' : IDL.Text,
    'contactNotes' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptAdminInvitation' : IDL.Func([], [], []),
    'addOrUpdateTrackingNumber' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignAdminRoleToCaller' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'checkAdminInvitation' : IDL.Func([], [IDL.Bool], ['query']),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ShippingAddress, IDInformation],
        [IDL.Nat],
        [],
      ),
    'declineAdminInvitation' : IDL.Func([], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBannedUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isBannedUser' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAdminInvitation' : IDL.Func([IDL.Principal], [], []),
    'sendAdminInvitationByEmail' : IDL.Func([IDL.Text], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'updateOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ShippingAddress,
          IDInformation,
          OrderStatus,
          PaymentContactStatus,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updatePaymentContactStatus' : IDL.Func(
        [IDL.Nat, PaymentContactStatus, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };